services:
    tabby:
        build: .
        restart: always
        command: /bin/sh -c "[ -d /app-dist/1.0.189-nightly.2 ] || ./manage.sh add_version 1.0.189-nightly.2; ./start.sh"
        volumes:
        - ./app-dist:/app-dist
        - ./data:/data
        ports:
        - 9090:80
        environment:
        - DATABASE_URL=sqlite:////data/db.sqlite3
        - PORT=80
        - DEBUG=False
        - SOCIAL_AUTH_GITHUB_KEY=xxx
        - SOCIAL_AUTH_GITHUB_SECRET=yyy
        # - APP_DIST_STORAGE="file:///app-dist"